# Generated by Django 4.1.7 on 2023-04-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='classroom',
            new_name='Level_of_study',
        ),
    ]
