# Generated by Django 4.1.7 on 2023-04-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_classroom_user_level_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='level_of_study',
            field=models.CharField(choices=[('FRESHMAN', 'Freshman'), ('SOPHOMORE', 'Sophomore'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('GRADUATE', 'Graduate')], max_length=100),
        ),
    ]
